apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-ms
  template:
    metadata:
      labels:
        app: notification-ms
    spec:
      containers:
        - name: notification-ms
          image: kams97/notification_service:latest
          ports:
            - containerPort: 8000
          env:
            - name: BASIC_AUTH_USERNAME
              value: "admin"
            - name: BASIC_AUTH_PASSWORD
              value: "secret123"
            - name: ENV
              value: "production"
            - name: DEBUG
              value: "False"
          livenessProbe:
            httpGet:
              path: /v1/healthcheck/live
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/healthcheck/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"